### ISSUE TITLE
Just wanna say something

### ISSUE THREAD

**Issue by moeenio** [Rexxt/buttons#1]
You should put yourself as a public member of Rexxt Software so other people can see you are in it.

**Comment by Rexxt** [comment]
?

**Comment by moeenio** [comment]
On the Rexxt Software organisation's page, you can show up yourself as a public member so other people can see that you are in the organisation.

**Comment by Rexxt** [comment]
I can see myself...

**Comment by moeenio** [comment]
But people not in the organisation can't see you and @Jack10101 !
